theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  debug:
    active: true
    productionUrl: https://example.osuny.org
  logo:
    header:
      default: "/assets/images/logo.svg"
      darkmode: "/assets/images/logo-white.svg"
    footer:
      default: "/assets/images/logo.svg"
      darkmode: "/assets/images/logo-white.svg"
  search:
    active: true
    appearance: both
    position: top-menu
  organizations:
    single:
      backlinks: true
  persons:
    single:
      backlinks: true