theme: rennes-hugo-theme
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  debug:
    active: true
    productionUrl: https://example.osuny.org
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/monogramme-blanc.svg"
  search:
    active: true
  organizations:
    single:
      backlinks: true
  persons:
    single:
      backlinks: true
  menu:
    dropdown:
      linkToLevel1: false
