
es:
  title: >-
    Example
  contentDir: content/en
  languageCode: es
  languageName: Castillano
  params:
    social:
      email: >-
        contact@osuny.org
      mastodon: >-
        https://www.linkedin.com/company/osuny/
      peertube: >-
        https://www.linkedin.com/company/osuny/
      x: >-
        https://x.com/noesya_coop?lang=fr
      github: >-
        https://github.com/osunyorg
      linkedin: >-
        https://www.linkedin.com/company/osuny/
      vimeo: >-
        https://vimeo.com/noesya
      instagram: >-
        https://www.linkedin.com/company/osuny/
      facebook: >-
        https://www.linkedin.com/company/osuny/
      tiktok: >-
        https://www.linkedin.com/company/osuny/
  permalinks:
    posts: /actualites-1/:year-:month-:day-:slug/
    posts_categories: /actualites-1/:slug/
    events: /agenda/:year-:month-:day-:slug/
    events_categories: /agenda/:slug/
    projects: /projects/:year-:slug/
    projects_categories: /projects/:slug/
    locations: /campus/:slug/
    diplomas: /diplomas/:slug/
    programs: /formations/:slug/
    publications: /publications/:year-:slug/
    organizations: /organisations/:slug/
    organizations_categories: /organisations/categories/:slug/
    persons: /equipe/:slug/
    persons_categories: /equipe/categories/:slug/
    administrators: /equipe/:slug/roles/
    authors: /equipe/:slug/actualites-1/
    researchers: /equipe/:slug/publications/
    teachers: /equipe/:slug/programs/
  taxonomies:
    administrator: administrators
    author: authors
    diploma: diplomas
    events_category: events_categories
    location: locations
    organizations_category: organizations_categories
    persons_category: persons_categories
    posts_category: posts_categories
    projects_category: projects_categories
    researcher: researchers
    teacher: teachers
    volume: volumes# DO NOT EDIT THIS FILE BY HAND - IT WILL BE OVERWRITTEN BY OSUNY

en:
  title: >-
    Example
  contentDir: content/en
  languageCode: en
  languageName: English
  params:
    social:
      email: >-
        contact@osuny.org
      mastodon: >-
        https://www.linkedin.com/company/osuny/
      peertube: >-
        https://www.linkedin.com/company/osuny/
      x: >-
        https://x.com/noesya_coop?lang=fr
      github: >-
        https://github.com/osunyorg
      linkedin: >-
        https://www.linkedin.com/company/osuny/
      vimeo: >-
        https://vimeo.com/noesya
      instagram: >-
        https://www.linkedin.com/company/osuny/
      facebook: >-
        https://www.linkedin.com/company/osuny/
      tiktok: >-
        https://www.linkedin.com/company/osuny/
  permalinks:
    posts: /actualites-1/:year-:month-:day-:slug/
    posts_categories: /actualites-1/:slug/
    events: /agenda/:year-:month-:day-:slug/
    events_categories: /agenda/:slug/
    projects: /projects/:year-:slug/
    projects_categories: /projects/:slug/
    locations: /campus/:slug/
    diplomas: /diplomas/:slug/
    programs: /formations/:slug/
    publications: /publications/:year-:slug/
    organizations: /organisations/:slug/
    organizations_categories: /organisations/categories/:slug/
    persons: /equipe/:slug/
    persons_categories: /equipe/categories/:slug/
    administrators: /equipe/:slug/roles/
    authors: /equipe/:slug/actualites-1/
    researchers: /equipe/:slug/publications/
    teachers: /equipe/:slug/programs/
  taxonomies:
    administrator: administrators
    author: authors
    diploma: diplomas
    events_category: events_categories
    location: locations
    organizations_category: organizations_categories
    persons_category: persons_categories
    posts_category: posts_categories
    projects_category: projects_categories
    researcher: researchers
    teacher: teachers
    volume: volumes
fr:
  title: >-
    Example
  contentDir: content/fr
  languageCode: fr
  languageName: Français
  params:
    social:
      email: >-
        contact@osuny.org
      mastodon: >-
        https://www.linkedin.com/company/osuny/
      peertube: >-
        https://www.linkedin.com/company/osuny/
      x: >-
        https://x.com/noesya_coop?lang=fr
      github: >-
        https://github.com/osunyorg
      linkedin: >-
        https://www.linkedin.com/company/osuny/
      vimeo: >-
        https://vimeo.com/noesya
      instagram: >-
        https://www.linkedin.com/company/osuny/
      facebook: >-
        https://www.linkedin.com/company/osuny/
      tiktok: >-
        https://www.linkedin.com/company/osuny/
  permalinks:
    posts: /actualites/:year-:month-:day-:slug/
    posts_categories: /actualites/:slug/
    events: /agenda/:year-:month-:day-:slug/
    events_categories: /agenda/:slug/
    projects: /projets/:year-:slug/
    projects_categories: /projets/:slug/
    locations: /campus/:slug/
    diplomas: /diplomes/:slug/
    programs: /offre-de-formation/:slug/
    publications: /publications/:year-:slug/
    organizations: /organisations/:slug/
    organizations_categories: /organisations/categories/:slug/
    persons: /equipe/:slug/
    persons_categories: /equipe/categories/:slug/
    administrators: /equipe/:slug/roles/
    authors: /equipe/:slug/actualites/
    researchers: /equipe/:slug/publications/
    teachers: /equipe/:slug/programs/
  taxonomies:
    administrator: administrators
    author: authors
    diploma: diplomas
    events_category: events_categories
    location: locations
    organizations_category: organizations_categories
    persons_category: persons_categories
    posts_category: posts_categories
    projects_category: projects_categories
    researcher: researchers
    teacher: teachers
    volume: volumes
