on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 2 * * *'

name: 'Daily W3C Validation'

jobs:
  validate:
    timeout-minutes: 120
    runs-on: ubuntu-latest

    name: 'Validate against W3C'
    strategy:
      matrix:
        url:
          - https://example.osuny.org/fr/
          - https://example.osuny.org/fr/offre-de-formation/
          - https://example.osuny.org/fr/offre-de-formation/animation-sociale-et-socioculturelle/
          - https://example.osuny.org/fr/actualites/
          - https://example.osuny.org/fr/actualites/2023-03-04-referentiel-general-decoconception-de-services-numeriques-rgesn/
          - https://example.osuny.org/fr/equipe/
          - https://example.osuny.org/fr/equipe/arnaud-levy/
          - https://example.osuny.org/fr/organisations/noesya/
          - https://example.osuny.org/fr/blocks/tous-les-blocks/
    steps:
      - name: Send request to W3C with URL to validate
        run: |
          curl -G "https://validator.w3.org/nu/" --data-urlencode "doc=${{ matrix.url }}" --data-urlencode "out=json" > w3c-response.json
      - name: Send JSON response to webhook
        run: |
          curl --write-out '%{http_code}' --silent --output /dev/null -X POST -H "Content-Type: application/json" -H "X-Secret-Token: ${{ secrets.W3C_CI_API_SECRET }}" -d @w3c-response.json ${{ secrets.W3C_CI_API_URL }}
